### PR TITLE
docs: Add Markdown Any Decision Records to project

### PR DESCRIPTION
**Pull request by ghost**
This pull request proposes to add Markdown Any Decision Records to the project.

Discuss any thoughts or ideas you have in Pull requests comments.
If they're substantive, consider adding them as a commit to the markdown files.

### CODE REVIEW

**Comment by tinkerwilco** [comment]
nice. I haven't used MADR before but the idea sounds in alignment with my general understanding of progressive development practices! I'll have to look into this more.

**Comment by ghost** [comment]
@tinkerwilco Here's where I first learned about MADRs in particular: https://adr.github.io/madr/

**Comment by tinkerwilco** [comment]
https://medium.com/olzzio/the-markdown-adr-madr-template-explained-and-distilled-b67603ec95bb
I've got some reading to do!

**Comment by ghost** [comment]
One alternative idea for our templates: Human-friendly language.

In my initial commit, I chose to keep the language from the MADR docs:

* Context and Problem Statement
* Considered Options
* Decision Outcome

This is efficient and technically correct, but impersonal.

One thing I've tried to do at my workplace is frame things in human-centric language.
Such as:

* What are we trying to decide?
* What alternatives are there?
* What did we decide?

The language on those questions might need some wordsmithing,
but the idea is to **ask human questions** rather than **have impersonal headings**.
I've found that I skip details with impersonal headings 
that I instead document when asked questions.

**Comment by ej838639** [comment]
This is a great idea. It will help us track why we are chose a tool or approach. I agree that human-centric language would make the template even better. I'll merge this for now so we can get started with it. We can incorporate this idea once we accumulate other template enhancements as we make MADRs.

**Comment by ej838639** [comment]
@rowlandcodes Why did you put the markdown files in docs/madr/decision instead of docs/madr? What other folders do you envision under docs/madr?

**Comment by ghost** [comment]
This folder design allows for `docs/madr` to have a `README.md`,
In case we wanted a general statement about what ADRs were and how they worked.

Feel free to re-arrange the folder structure.

**Pull request merged**
